version: '3.8'

services:
  db:
    image: postgis/postgis:17-3.5
    container_name: database
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matcha
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=adminpassword
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"

volumes:
  db_data:
  s3_data:
