version: '3.8'

services:
  db:
    image: postgis/postgis:17-3.5
    container_name: database
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matcha
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
